## practice

### number 1

 with your high school reunion fast approaching you decide to get in shape and lose some
weight you record your weight every day for five weeks starting on a monday
given these daily weights build an array with your average weight per weekend

In [38]:
import numpy as np 

In [39]:
dailywts = 185-np.arange(5*7)/5
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


## Solution

In [40]:
shanbehaa = dailywts[5::7]

In [45]:
shanbehaa

array([184. , 182.6, 181.2, 179.8, 178.4])

In [46]:
jomeha = dailywts[6::7]
jomeha

array([183.8, 182.4, 181. , 179.6, 178.2])

In [47]:
(shanbehaa+jomeha)/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

### number 2

to become a gold miner you decide to prospect five locations underneath a 7x7 grid of land how much gold do you uncover at each location

In [48]:
import numpy as np
np.random.seed(72)
gold = np.random.randint(0,10,size=(7,7))
print(gold)

[[8 3 5 5 7 5 8]
 [0 8 5 1 0 7 0]
 [2 8 4 2 3 9 1]
 [6 1 5 7 8 3 5]
 [3 0 5 7 8 5 5]
 [0 3 8 2 1 6 8]
 [0 2 9 3 6 7 3]]


In [49]:
locs = np.array([
        [0,4],
        [2,2],
        [2,3],
        [5,1],
        [6,3]
])
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


## Solution

In [54]:
gold[locs[:,0],locs[:,1]].sum()

19

### number 3

you decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken
restaurant,Chic-fil-A. you buy three billboards evenly spaced
starting on mile marker 17 and ending on mile marker 28 then you buy another three billboards
evenly spaced starting on mile marker 32 and ending on mile marker 36. in order
from mile marker 17 to 36 your billboards display these ads a,b,c
c,b,a determine how far each c ad is from your restaurant which is
located at mile marker 30.

## Solution

In [64]:
a = np.abs(np.array([np.linspace(17,28,3),  np.linspace(32,36,3)]) - 30)


In [65]:
a[[0,1],[2,0]]

array([2., 2.])

### number 4

scientist and you've developed a questionnaire that determines a person's love score a real valued number between
zero and a hundred your theory is that two people with similar love scores should make a good match
given the love scores for 10 different people create a matrix where element ij gives the absolute difference of the
love scores for person i and person j

In [19]:
import numpy as np
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(0,100,size=10),2)

print(love_scores)

[ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]


## Solution

In [ ]:
#

### number 5

one of your pet peeves is when students rush through their exams to teach them a lesson
you decide to give zeroes to the first three students who score less than 60 in the order they turned in their
exams so given a 1d array of integers identify the first three values less than 60
and replace them with zero

In [21]:
import numpy as np 
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(30,100,15))
print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


## Solution

In [ ]:
#

### number 6

Eager to make your mark on PTA,you decide the best way to hide eggs for the upcoming easter egg hunt is to use numpy
you represent the field as a 10 by 10 array of zeros now your goal is to insert 20 random
normal values at random non-repeating locations in the grid that tell you how much candy to hide at
each spot and where 

In [23]:
import numpy as np
field = np.zeros(shape=(10,10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Solution

In [ ]:
#

### number 7

your given a  10x2 array of floats where each row represents a movie the first column represents the movie's
rating and the second column represents the director's rating your goal is to create a third column to
represent the overall rating the overall rating is equal to the movie rating if it exists
otherwise it's the director's rating

In [32]:
import numpy as np 
generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(0.0,10.0,size=(10,2)))
ratings[[1,2,7,9],[0,0,0,0]] = np.nan
ratings

array([[ 7.,  1.],
       [nan,  2.],
       [nan,  8.],
       [ 9.,  3.],
       [ 8.,  9.],
       [ 5.,  2.],
       [ 8.,  2.],
       [nan,  6.],
       [ 9.,  2.],
       [nan,  5.]])

## Solution

In [ ]:
#

### number 8

10 fish occupy a 5x5x5 grid of water each fish decides to move to a new (i,j,k)
location given by the matrix below if multiple fish end up occupying the same cell the
biggest fish eats the smaller fish determine which fish will survive

In [34]:
import numpy as np
locs = np.array([[
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
]])
locs

array([[[0, 0, 0],
        [1, 1, 2],
        [0, 0, 0],
        [2, 1, 3],
        [5, 5, 4],
        [5, 0, 0],
        [5, 0, 0],
        [0, 0, 0],
        [2, 1, 3],
        [1, 3, 1]]])

In [36]:
generator = np.random.default_rng(1010)
weights = generator.integers(10,40,size=10)
weights

array([30, 12, 30, 26, 10, 37, 13, 39, 35, 35], dtype=int64)