## practice

### number 1

 with your high school reunion fast approaching you decide to get in shape and lose some
weight you record your weight every day for five weeks starting on a monday
given these daily weights build an array with your average weight per weekend

In [38]:
import numpy as np 

In [39]:
dailywts = 185-np.arange(5*7)/5
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


## Solution

In [40]:
shanbehaa = dailywts[5::7]

In [45]:
shanbehaa

array([184. , 182.6, 181.2, 179.8, 178.4])

In [46]:
jomeha = dailywts[6::7]
jomeha

array([183.8, 182.4, 181. , 179.6, 178.2])

In [47]:
(shanbehaa+jomeha)/2

array([183.9, 182.5, 181.1, 179.7, 178.3])

### number 2

to become a gold miner you decide to prospect five locations underneath a 7x7 grid of land how much gold do you uncover at each location

In [48]:
import numpy as np
np.random.seed(72)
gold = np.random.randint(0,10,size=(7,7))
print(gold)

[[8 3 5 5 7 5 8]
 [0 8 5 1 0 7 0]
 [2 8 4 2 3 9 1]
 [6 1 5 7 8 3 5]
 [3 0 5 7 8 5 5]
 [0 3 8 2 1 6 8]
 [0 2 9 3 6 7 3]]


In [49]:
locs = np.array([
        [0,4],
        [2,2],
        [2,3],
        [5,1],
        [6,3]
])
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


## Solution

In [54]:
gold[locs[:,0],locs[:,1]].sum()

19

### number 3

you decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken
restaurant,Chic-fil-A. you buy three billboards evenly spaced
starting on mile marker 17 and ending on mile marker 28 then you buy another three billboards
evenly spaced starting on mile marker 32 and ending on mile marker 36. in order
from mile marker 17 to 36 your billboards display these ads a,b,c
c,b,a determine how far each c ad is from your restaurant which is
located at mile marker 30.

## Solution

In [64]:
a = np.abs(np.array([np.linspace(17,28,3),  np.linspace(32,36,3)]) - 30)


In [65]:
a[[0,1],[2,0]]

array([2., 2.])

### number 4

scientist and you've developed a questionnaire that determines a person's love score a real valued number between
zero and a hundred your theory is that two people with similar love scores should make a good match
given the love scores for 10 different people create a matrix where element ij gives the absolute difference of the
love scores for person i and person j

In [64]:
import numpy as np
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(0,100,size=10),2)

print(love_scores)

[94.2  13.45 57.64 19.67 68.94 50.22 55.99 90.09 61.14 27.88]


## Solution

In [ ]:
#

In [52]:
x = np.abs( love_scores[np.newaxis,:] - love_scores[:,np.newaxis])
x

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11,
        55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19,
        11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38,
        27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76,
        33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49,
        20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,
         9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55,
        23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,
         8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  ,
        56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,
         0.  ]])

(10, 1)

### number 5

one of your pet peeves is when students rush through their exams to teach them a lesson
you decide to give zeroes to the first three students who score less than 60 in the order they turned in their
exams so given a 1d array of integers identify the first three values less than 60
and replace them with zero

In [71]:
import numpy as np 
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(30,100,15))
print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


## Solution

In [ ]:
#

In [80]:
scores[(scores <60).nonzero()[0][:3]] = 0
scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

### number 6

Eager to make your mark on PTA,you decide the best way to hide eggs for the upcoming easter egg hunt is to use numpy
you represent the field as a 10 by 10 array of zeros now your goal is to insert 20 random
normal values at random non-repeating locations in the grid that tell you how much candy to hide at
each spot and where 

In [100]:
import numpy as np
field = np.zeros(shape=(10,10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Solution

In [ ]:
#

In [107]:
np.set_printoptions(linewidth=999)
generator = np.random.default_rng(300)
vals = np.round(generator.normal(size = 20),2)
loc_row = generator.choice(10, len(vals), replace= True)
generator = np.random.default_rng(100)
loc_col = generator.choice(10, len(vals), replace= True)
field[loc_row, loc_col] = vals
field

array([[ 0.  , -0.05,  0.  ,  0.  ,  0.  ,  0.68,  0.  ,  0.  , -0.08,  0.  ],
       [ 0.  ,  0.  , -0.71,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.29,  0.24],
       [ 0.  ,  0.  ,  0.09,  0.  ,  0.08, -0.84,  0.  , -0.28,  0.  , -0.71],
       [-0.78,  0.  ,  0.  , -0.94,  0.  ,  0.  ,  0.  ,  0.43,  0.  ,  0.  ],
       [ 0.  ,  0.  , -0.28, -0.78,  0.72, -0.98,  0.  ,  0.  ,  0.  ,  0.  ],
       [-0.08,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.94,  0.  ],
       [ 0.  ,  0.26,  0.  , -0.05,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.68],
       [ 0.72,  0.31,  0.  ,  0.  , -0.98, -0.02,  0.08, -0.84,  0.  ,  0.26],
       [-1.74,  0.  ,  0.  ,  0.  , -0.71,  0.24,  0.  ,  0.09,  0.  ,  0.  ]])

In [105]:
field.flatten()

x = np.arange(100).reshape(25,2,2)

x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### number 7

your given a  10x2 array of floats where each row represents a movie the first column represents the movie's
rating and the second column represents the director's rating your goal is to create a third column to
represent the overall rating the overall rating is equal to the movie rating if it exists
otherwise it's the director's rating

In [109]:
import numpy as np 
generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(0.0,10.0,size=(10,2)))
ratings[[1,2,7,9],[0,0,0,0]] = np.nan
ratings

array([[ 7.,  1.],
       [nan,  2.],
       [nan,  8.],
       [ 9.,  3.],
       [ 8.,  9.],
       [ 5.,  2.],
       [ 8.,  2.],
       [nan,  6.],
       [ 9.,  2.],
       [nan,  5.]])

## Solution

In [121]:
x = np.where(np.isnan(ratings[:,0]), ratings[:,1], ratings[:,0]  )
result = np.insert(ratings, values = x , axis = 1, obj=2)
print(result)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]


### number 8

10 fish occupy a 5x5x5 grid of water each fish decides to move to a new (i,j,k)
location given by the matrix below if multiple fish end up occupying the same cell the
biggest fish eats the smaller fish determine which fish will survive

In [34]:
import numpy as np
locs = np.array([[
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
]])
locs

array([[[0, 0, 0],
        [1, 1, 2],
        [0, 0, 0],
        [2, 1, 3],
        [5, 5, 4],
        [5, 0, 0],
        [5, 0, 0],
        [0, 0, 0],
        [2, 1, 3],
        [1, 3, 1]]])

In [166]:
generator = np.random.default_rng(1010)
weights = generator.integers(10,40,size=10)
weights

array([30, 12, 30, 26, 10, 37, 13, 39, 35, 35], dtype=int64)

## Solution

In [167]:
weights.argsort()

array([4, 1, 6, 3, 0, 2, 8, 9, 5, 7], dtype=int64)

### number 9

you own a taco truck thats open 24/7 and you manage five employees who run it employees work solo eight-hour shifts you decide the
best way to set their schedule for the upcoming week is to create a bunch of random schedules and select the one that looks best
you build a 1000 by 21 array of random employee ids where element (i,j) gives the employee id
working shift j for schedule i a schedule is valid as long as no employee works two
consecutive shifts get the row index of all valid schedules

In [2]:
import numpy as np
generator = np.random.default_rng(999)
schedules = generator.integers(0,5,size= (1000,21))
print(schedules)

[[4 3 0 ... 2 0 0]
 [2 4 3 ... 3 3 2]
 [1 0 1 ... 1 2 1]
 ...
 [2 2 1 ... 3 1 4]
 [1 0 3 ... 2 3 2]
 [1 1 4 ... 2 4 2]]


## Solution

In [ ]:
#

### number 10

you manage a local department for the Census. responsible for measuring the population of each block in the city where you live
even though you could do it yourself for each of the last five years you've tasked this job to your subordinate ,jim
what jim gives you each year is a 2x4 array of his population estimates
where each element of the array represents a city block after five years you have a five by two
by four array of population estimates called gym where i,j,k represents
jim's population estimate for block jk in your eye the thing is
you don't fully trust jim's estimates because you see him spending an ungodly amount of time on facebook
so each year you go behind his back and measure the population of two city blocks after five years
you have the following data blocks a five by two by two array indicating
which blocks you measured each year where i j gives the coordinates for the
jth block you measured in year i and pops a corresponding 5x2 array
with the population you measured for the jth block in year i how many times was jim's estimate at
least 10 higher or lower than your estimate.

In [5]:
import numpy as np 
generator = np.random.default_rng(2357)
jim = np.round(generator.normal(100,5,size=(5,2,4)))
print(jim)

[[[106. 103.  92. 100.]
  [ 94. 102.  94. 100.]]

 [[104.  96. 109.  96.]
  [101. 104. 102.  92.]]

 [[102. 102. 108. 101.]
  [ 91. 101. 106.  99.]]

 [[101.  98.  95. 102.]
  [100. 101.  99.  93.]]

 [[107. 101. 104. 105.]
  [102.  97. 101. 102.]]]


In [7]:
blocks = np.array([
    [[0,2],[1,3]],
    [[1,2],[0,0]],
    [[0,0],[1,2]],
    [[1,1],[0,3]],
    [[0,1],[1,0]]
])

In [9]:
pops = np.array([
    [100,105 ],
    [110,92],
    [95,99],
    [95,99],
    [89,107],
    [101,98]
])

## Solution

In [ ]:
#

### number 11

given 10x10x10 array of zeros set (i,j,k)=1 if all of the following hold true 
1. i is odd
2. j is even
3. and k is prime
in other words set these elements to one : ((1,0,2),(1,0,3,...))

In [160]:
import numpy as np 
chawy = np.zeros((10,10,10))
chawy[:2]

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

## Solution

In [164]:
i= np.array([1,3,5,7,9])
j = np.array([0,2,4,6,8])
k = np.array([2,3,5,7])

chawy[i[:,np.newaxis, np.newaxis], j[np.newaxis,:, np.newaxis], k[np.newaxis,np.newaxis, :]] = 1

chawy

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

### number 12

you're preparing for a game show where you play the following game:
you're faced with four doors behind one
door is cash money and behind the other three doors is a steaming pile of broccoli
if you pick the door with money you get the option to play again at the risk of losing the money you've collected thus far
if you keep winning you can play a maximum of three rounds before the game show host kicks you off his show you have some
strategy ideas you'd like to evaluate before you go on the show so you hired an unpaid intern to scour
through historic recordings of the show and log data on where prizes were located
and the value of each prize your intern gets back to you with the following matrices

* ``prize_doors`` a 5x3 array where element (i,j) gives the door hiding the prize in the
jth round of the ith game and 
* ``prizes`` a 5x3 array where element (i,j) gives the prize amount in round j of the ith game 

build a 5x3x4 matrix
where i j k represents the prize behind door k of round j of game i

In [19]:
import numpy as np 
prize_doors = np.array([
    [1,0,2],
    [0,0,1],
    [3,3,1],
    [1,2,0],
    [2,1,1]
])

prizes = np.array([
    [100,150,500],
    [200,300,250],
    [150,100,325],
    [425,200,100],
    [200,250,300]
])

## Solution

In [ ]:
#

### number 13

given ``peanut``a 4x5 array of zeros and ``butter`` a five element 1d array of indices
fill the rows of peanut with ones starting from the column indices given by butter 

In [21]:
peanut = np.zeros((4,5))
peanut

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
butter = np.array([3,0,4,1])
print(butter)

[3 0 4 1]


## Solution

In [ ]:
#

### number 14

given an array of integers, one hot encode it into 2d array

In [23]:
import numpy as np 
yo = np.array([3,1,0,1])

## Solution

In [ ]:
#

array([[[6, 6]]])