In [155]:
import numpy as np

In [161]:
square = np.array([
    [16,  3,  2, 13],
    [ 5, 10, 11,  8],
    [ 9,  6,  7, 12],
    [ 4, 15, 14,  1],
])
square.shape

(4, 4)

In [160]:
for i in range(4):
    print(square[i,:])
    print("axis 0:",i, square[i,:].sum())
    print(square[:,i])
    print("axis 1:",i, square[:,i].sum())
    

[16  3  2 13]
axis 0: 0 34
[16  5  9  4]
axis 1: 0 34
[ 5 10 11  8]
axis 0: 1 34
[ 3 10  6 15]
axis 1: 1 34
[ 9  6  7 12]
axis 0: 2 34
[ 2 11  7 14]
axis 1: 2 34
[ 4 15 14  1]
axis 0: 3 34
[13  8 12  1]
axis 1: 3 34


In [162]:
square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [165]:
square[:2,:2].sum()

34

In [167]:
square[1:3,1:3].sum()

34

In [171]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [184]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [207]:
b = np.array([1,np.nan, 2,np.nan,3])
b

array([ 1., nan,  2., nan,  3.])

In [205]:
b.dtype

dtype('float64')

In [204]:
b[~np.isnan(b)]

array([1., 2., 3.])

In [222]:
a =b  = np.array([[4,8],[2,5]])


In [225]:
np.concatenate((a,b), axis=0)

array([[4, 8],
       [2, 5],
       [4, 8],
       [2, 5]])

In [ ]:
T
sort
concatenate


In [226]:
import seaborn as sns


In [228]:
df = sns.load_dataset("titanic")
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [231]:
df.mean()

C:\Users\rasoo\AppData\Local\Temp\ipykernel_11148\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


survived       0.383838
pclass         2.308642
age           29.699118
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
dtype: float64